### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by alickbass** [llvm-swift/ClangSwift#25]
Hi! Thanks a lot for this great project! I was wondering if installation steps are the same as in the LLVMSwift? Thanks!

**Comment by alickbass** [comment]
Because when I try to load it with Package Manager:

```swift
import PackageDescription

let package = Package(
    name: "SwiftClang",
    dependencies: [
         .package(url: "https://github.com/llvm-swift/ClangSwift", from: "0.0.4"),
    ],
    targets: [
        .target(
            name: "SwiftClang",
            dependencies: ["Clang"]),
    ]
)
```
I get an error when I try to build: `'clang-c/Platform.h' file not found`

**Comment by alickbass** [comment]
When installing LLVM with brew, forgot to use `--with-toolchain` flag and it solved the problem

**Comment by harlanhaskins** [comment]
We could definitely use some more information in the README if you're up for it.

**Comment by alickbass** [comment]
I think that it would be great... The setup steps are not obvious, tbh. I would rather have a checklist that works for everybody even without googling how to properly install the llvm with the toolchain...
