### ISSUE TITLE
Unexpected optional promotion

### ISSUE THREAD

**Issue by ddddxxx** [llvm-swift/ClangSwift#27]
https://github.com/llvm-swift/ClangSwift/blob/50533ce84c959e70b424f12ba9a7ad175e621d64/Sources/Clang/CTypes.swift#L268-L269

This conversion always succeed. Should we remove the optional mark or return nil for InvalidType?

**Comment by harlanhaskins** [comment]
I'd say return `nil` for `InvalidType`.
