### ISSUE TITLE
Is there a way to use this wrapper with Xcode toolchain?

### ISSUE THREAD

**Issue by s1ddok** [llvm-swift/ClangSwift#38]
I wonder if there is way to link to libclang that comes with `Xcode.app`? I want to make a small tool based on this library and I wish I can avoid forcing users to install llvm via brew on their systems, because it takes a lot of time.

**Comment by CodaFi** [comment]
I don’t think the headers get shipped with the toolchain’s copy of libClang so unfortunately that’s not going to work.  The brew installation process for LLVM only takes a while until they get the bottles built, then it’s usually a breeze.
